name: Post and Deploy
on:
  release:
    types:
      - published
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        miniconda-version: py37_4.10.3
        auto-activate-base: true
        activate-environment: ""
    - name: Install AE5 Tools
      shell: bash -l {0}
      run: conda install -c defusco ae5-tools=0.4.1+21 -y
    - name: Post Metadata
      env:
        AE5_HOSTNAME: ${{ secrets.AE5_HOSTNAME }}
        AE5_USERNAME: ${{ secrets.AE5_USERNAME }}
        AE5_PASSWORD: ${{ secrets.AE5_PASSWORD }}
      shell: bash -l {0}
      run: ae5 post revision-metadata --hostname $AE5_HOSTNAME --username  $AE5_USERNAME --password AE5_PASSWORD

