name: Post and Deploy
on:
  release:
    types:
      - published
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  post-metadata:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        miniconda-version: py37_4.10.3
        auto-activate-base: true
        activate-environment: ""
    - name: Install AE5 Tools
      shell: bash -l {0}
      run: conda install -c defusco ae5-tools=0.4.1+27 -y
    - name: AE5 Tools login
      shell: bash -l {0}
      run: ae5 login --hostname ${{ secrets.AE5_HOSTNAME }} --username  ${{ secrets.AE5_USERNAME }} --password ${{ secrets.AE5_PASSWORD }}
    - name: Post Metadata
      shell: bash -l {0}
      run: ae5 post revision-metadata --project-id ${{ secrets.AE5_PROJECT_ID }}
